- id: '1586813023430'
  alias: test
  description: test
  trigger:
  - event_data:
      action: turn_on_boiler
    event_type: mobile_app_notification_update
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: switch.switcher_webapi
    service: switch.turn_on
  - data:
      data:
        actions:
        - action: turn_on_boiler
          title: test
        message: ok-test
        title: ok-check
    service: notify.mobile_app_mi_9t_pro
