'background': center / cover no-repeat url("/local/image/wallpaper03.jpg") fixed

decluttering_templates: !include_dir_merge_named config/lovelace/decluttering_templates/

button_card_templates: !include_dir_merge_named config/lovelace/button_card_templates/
custom_header:
  tab_container_css: 'padding-bottom: 5px'
  all_tabs_css: 'padding-right: 16px; padding-left: 16px; --iron-icon-width: 28px; --iron-icon-height: 28px;'
  header_text: '{{ viewTitle }}'
  split_mode: true
  compact_mode: false
  footer_mode: false
  indicator_top: true
  #background: 'var(--cch-background)'
  voice_hide: true
  chevrons: false
  hide_help: true
  hide_unused: true
  hide_config: true
  # exceptions:
  #   - conditions:
  #       query_string: kiosk
  #     config:
  #       kiosk_mode: true
title: Wintrov Home
views:

# exceptions:
#   - conditions:
#       query_string: kiosk
#     config:
#       kiosk_mode: true
  # Main view
  - !include config/lovelace/view/main.yaml

      # - type: custom:mod-card
      #   card:
      #     type: custom:mini-media-player
      #     entity: media_player.living_room_speaker
      #     name: גוגל מיני
      #     background: /local/image/speaker.jpg
      #     artwork: cover
      #     artwork_border: true
      #     power_color: true
      #     show_source: full
      #     show_progress: ture
      #     show_tts: true
      #   style:
      #     border-radius: 10px
      #     border: solid 1px rgba(100,100,100,0.3)
      #     box-shadow: 3px 3px rgba(0,0,0,0.4)
  ## aquarium tab
  - !include config/lovelace/view/aquarium.yaml
  ## boiler panel tab
  - !include config/lovelace/view/boiler.yaml
  ## weather tab
  - !include config/lovelace/view/weather.yaml
  ## internet tab
  - !include config/lovelace/view/speedtest.yaml
  ## version / container control tab
  - !include config/lovelace/view/control.yaml
  ## xiaomi tab
  - !include config/lovelace/view/vacuum.yaml
  ## homekit light tab
  - !include config/lovelace/view/homekit.yaml
  ## Salon light \ kitchen tab
  - !include config/lovelace/view/livingroom.yaml
  ## Salon TV \ Saar Tv tab
  - !include config/lovelace/view/tv.yaml