title: Smart Sensor
icon: mdi:shield-home-outline
path: Xiaomi
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: title
        variables:
          - name: שליטה בכל התאורה

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: shoulder_blank_card   
          - type: custom:decluttering-card
            template: all_the_light
            variables:
              - image: local/image/salon.jpeg
              - direction1: right
              - entity: group.homelight
              - font_size: 18
              - text_color: white
              - tap_action: more_info
          - type: custom:button-card
            template: shoulder_blank_card   
      - type: vertical-stack
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - switch.sonoff_1000ad249f_1
              - switch.sonoff_1000ad249f_2
              - switch.sonoff_1000ad249f_3
              - switch.sonoff_1000a3c51a_1
              - switch.sonoff_1000a3c51a_2
              - switch.sonoff_1000a3c51a_3
  - type: vertical-stack
    cards:
        - type: custom:decluttering-card
          template: title
          variables:
            - name: תאורה חדר כביסה
          
        - type: entities
          show_header_toggle: false
          entities: 
            - type: 'custom:slider-entity-row'
              entity: input_number.bathroom_lights_without_motion 
              name: זמן לכיבוי תאורה

            - entity: switch.bathroom_light
              name: מצב תאורה
            - entity: automation.bathroom_light_off
              name: אוטומצית הפעלת תאורה בתנועה
            - entity: input_datetime.bathroom_start_time
              name: שעת התחלה
            - entity: automation.bathroom_light_off
              name: אוטומצית כיבוי תאורה בתנועה
            - entity: input_datetime.bathroom_end_time
              name: שעת כיבוי
             # name: כיבוי לאחר זמן שאין תנועה

  - type: vertical-stack
    cards:
        - type: custom:decluttering-card
          template: title
          variables:
            - name: מנורת מטבח
          
        - type: entities
          show_header_toggle: false
          entities: 
            - type: custom:slider-entity-row
              entity: light.gateway_light_04cf8cf40276
            - automation.xiaomi_light_start
            - entity: input_datetime.xiaomi_light_timer_on
            - automation.xiaomi_light_end
            - entity: input_datetime.xiaomi_light_timer_off
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: title
        variables:
          - name: -מצב סוללות-

      - type: entities
        tap_action:
          action: none
        entities:
          - sensor.door_battery_sensor
          - sensor.smart_battery_sensor
          - sensor.switch_battery_sensor
          - sensor.motion_battery_sensor_1
          - sensor.motion_battery_sensor_2
          - sensor.motion_battery_sensor_3

      - type: custom:decluttering-card
        template: title
        variables:
          - name: -מצב חיישני תנועה-

      - type: entities
        tap_action:
          action: none
        entities:
          - sensor.door_status_state
          - sensor.switch_status_state
          - sensor.motion_1_status_state
          - sensor.motion_2_status_state
          - sensor.motion_3_status_state
          - sensor.getway_hub_lm