title: TV
icon: fas:tv
path: tv  
cards:

  - type: custom:layout-card
    #column_width: 250
    #column_height: 250
    layout: horizontal
    cards:
      - type: custom:decluttering-card
        template: title
        variables:
          - name: טלוויזית סלון
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            color_type: card
            template: power_button
            name: On\Off
            entity: media_player.salon_tv
          - type: "custom:button-card"
            color_type: card
            template: volume_button
            icon: mdi:volume-plus
            entity: media_player.salon_tv
            name: "volume plus"
            tap_action: 
              service: media_player.volume_up
              action: call-service             
              service_data:
                entity_id: media_player.salon_tv
          - type: "custom:button-card"
            color_type: card
            template: volume_button
            icon: mdi:volume-minus
            entity: media_player.salon_tv
            name: "volume down"
            tap_action: 
              service: media_player.volume_down
              action: call-service             
              service_data:
                entity_id: media_player.salon_tv

  - type: custom:layout-card
    #column_width: 250
    #column_height: 250
    layout: horizontal
    cards:
      - type: custom:decluttering-card
        template: title
        variables:
          - name: טלויזיה בחדר של סער
          
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            color_type: card
            template: power_button
            name: On\Off
            entity: media_player.saar_tv
          - type: "custom:button-card"
            color_type: card
            template: volume_button
            icon: mdi:volume-plus
            name: "volume up"
            entity: media_player.saar_tv
            tap_action: 
              service: media_player.volume_up
              action: call-service             
              service_data:
                entity_id: media_player.saar_tv
          - type: "custom:button-card"
            color_type: card
            template: volume_button
            icon: mdi:volume-minus
            name: "volume down"
            entity: media_player.saar_tv
            tap_action: 
              service: media_player.volume_down
              action: call-service             
              service_data:
                entity_id: media_player.saar_tv