#########################################################################
#                                                                       #
#                          Weather  Telegream                           #
#                                                                       #
########################################################################
telegram_weather:
  alias: 'weather_telegram'
  sequence:
  - data:
      data:
        photo:
          caption: מזג אוויר בעפולה
          url: https://www.yr.no/place/Israel/North_Israel/afula/meteogram.png
      message: Campainha
      title: Home Assistant
    service: notify.telegram
#########################################################################
#                                                                       #
#                          TIMER-ON Telegream                           #
#                                                                       #
########################################################################
backup_to_hardisk:
   alias: 'Backup Home Assitant img'
   sequence:
     - service: shell_command.homeassistant

update_homeassistant_container:
   alias: 'Update Home Assitant docker'
   sequence:
     - service: shell_command.homeassistant_updade
#########################################################################
#                                                                       #
#                          TIMER-ON Telegream                           #
#                                                                       #
########################################################################
turn_on_boiler:
    alias: 'turn_on_air'
    sequence:
      - service: notify.telegram
        data:
          #title: turn_on_boiler
          message: 'הופעל לוח זמנים לבוילר'
#########################################################################
#                                                                       #
#                          TIMER-OFF Telegream                          #
#                                                                       #
########################################################################
turn_off_boiler:
    alias: 'turn_off_boiler'
    sequence:
      - service: notify.telegram
        data:
          #title: turn_off_boiler
          message: 'כובה לוח זמנים לבוילר'
#########################################################################
#                                                                       #
#                             Now in home                               #
#                                                                       #
########################################################################
check_saarhome_version:
   sequence:
      - service: mqtt.publish
        data_template:
         topic: "cmnd/saarhome/status"
         payload: 2
#########################################################################
#                                                                       #
#                             Temp TO oFF/ ON                           #
#                                                                       #
########################################################################
turn_on_air:
    alias: 'הדלקת מאוורר עליון לטלגרם'
    sequence:
      - service: notify.telegram
        data:
          title: '*Home Assistant*'
          message: "מצב מתג מאורר עליון השתנה ל *{{ states('switch.sonoff4')}}*


                    טמפרטורה השתנתה ל *{{ states('sensor.sonoff4')}}*"

turn_off_air:
    alias: 'כיבוי מאוורר עליון לטלגרם'
    sequence:
      - service: notify.telegram
        data:
          title: '*Home Assistant*'
          message: "מצב מתג מאורר עליון השתנה ל *{{ states('switch.sonoff4')}}*


                    טמפרטורה השתנתה ל *{{ states('sensor.sonoff4')}}*"


alexa_tts_temp_state:
    alias: Alexa air switch state
    sequence:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.saar_s_echo_dot
          message: '
            The Aquarium temp is {{ states("sensor.sonoff4") }} , The air Switch goes to {{ states("switch.sonoff4") }}'


vacuum_perentes:
  alias: חדר הורים
  icon: mdi:stairs
  mode: single
  sequence:
  - service: vacuum.send_command
    data_template:
      command: app_segment_clean
      entity_id: vacuum.roborock_vacuum_a08_2
      params: 16
vacuum_kitchen:
  alias: מטבח
  icon: mdi:stairs
  mode: single
  sequence:
  - service: vacuum.send_command
    data_template:
      command: app_segment_clean
      entity_id: vacuum.roborock_vacuum_a08_2
      params: 20
vacuum_bathroom:
  alias: אמבטיה
  icon: mdi:stairs
  mode: single
  sequence:
  - service: vacuum.send_command
    data_template:
      command: app_segment_clean
      entity_id: vacuum.roborock_vacuum_a08_2
      params: 17
vacuum_rachel:
  alias: חדר דחל
  icon: mdi:stairs
  mode: single
  sequence:
  - service: vacuum.send_command
    data_template:
      command: app_segment_clean
      entity_id: vacuum.roborock_vacuum_a08_2
      params: 18
vacuum_hallway:
  alias: מסדרון
  icon: mdi:stairs
  mode: single
  sequence:
  - service: vacuum.send_command
    data_template:
      command: app_segment_clean
      entity_id: vacuum.roborock_vacuum_a08_2
      params: 21
vacuum_saar:
  alias: חדר סער
  icon: mdi:stairs
  mode: single
  sequence:
  - service: vacuum.send_command
    data_template:
      command: app_segment_clean
      entity_id: vacuum.roborock_vacuum_a08_2
      params: 22
bathroom_perents:
  alias: מקלחת הורים
  icon: mdi:stairs
  mode: single
  sequence:
  - service: vacuum.send_command
    data_template:
      command: app_segment_clean
      entity_id: vacuum.roborock_vacuum_a08_2
      params: 23

#####################################################################################################################
living_room_shutter_open:
    alias: "Living room shutter open"
    sequence:
      - alias: "Shutter open"
        service: cover.open_cover
        data:
          entity_id: cover.livingroom_cover
#####################################################################################################################
living_room_shutter_close:
    alias: "Living room shutter close"
    sequence:
      - alias: "Shutter close"
        service: cover.close_cover
        data:
          entity_id: cover.livingroom_cover
#####################################################################################################################
living_room_shutter_stop:
    alias: "Living room shutter stop"
    sequence:
      - alias: "Shutter stop"
        service: cover.stop_cover
        data:
          entity_id: cover.livingroom_cover

############################################################################
#                                                                          #
#                          Turn ON Switcher with timer                     #
#                                                                          #
############################################################################

switcher_turn_on_timer_script_15:
  alias: 15 min On with Timer
  sequence:
      - delay:
          milliseconds: 100
      - service: rest_command.switcher_turn_on
        data_template:
          minutes: 15 #'{{ states.input_select.switcher_timer_minutes_input_select.state }}'
      - service: homeassistant.update_entity
        entity_id: sensor.switcher_webapi

switcher_turn_on_timer_script_30:
  alias: 30 min On with Timer
  sequence:
      - delay:
          milliseconds: 100
      - service: rest_command.switcher_turn_on
        data_template:
          minutes: 30 #'{{ states.input_select.switcher_timer_minutes_input_select.state }}'
      - service: homeassistant.update_entity
        entity_id: sensor.switcher_webapi
        
switcher_turn_on_timer_script_45:
  alias: 45 min On with Timer
  sequence:
      - delay:
          milliseconds: 100
      - service: rest_command.switcher_turn_on
        data_template:
          minutes: 45 #'{{ states.input_select.switcher_timer_minutes_input_select.state }}'
      - service: homeassistant.update_entity
        entity_id: sensor.switcher_webapi

switcher_turn_on_timer_script_60:
  alias: 60 On with Timer
  sequence:
      - delay:
          milliseconds: 100
      - service: rest_command.switcher_turn_on
        data_template:
          minutes: 60 #'{{ states.input_select.switcher_timer_minutes_input_select.state }}'
      - service: homeassistant.update_entity
        entity_id: sensor.switcher_webapi
