
###############################################################################
#- platform: broadlink_rpi
#  host: 192.168.1.3
#  mac: 'B4:43:0D:F0:7C:34'
#  type: 'sp3'
#  timeout: 15
#  retry: 5
###############################################################################
- platform: mqtt
  name: "Sonoff1"
  state_topic: "stat/Sonoff1/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/Sonoff1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
###############################################################################

- platform: mqtt
  name: "Sonoff8"
  state_topic: "stat/sonoff8/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff8/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
###############################################################################
- platform: mqtt
  name: "Sonoff2"
  state_topic: "stat/Sonoff2/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/Sonoff2/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
###############################################################################
- platform: mqtt
  name: "Sonoff3"
  state_topic: "stat/Sonoff3/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/Sonoff3/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
###############################################################################
- platform: mqtt
  name: "Sonoff4"
  state_topic: "stat/Sonoff4/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/Sonoff4/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
 ##############################################################################
- platform: mqtt
  name: "Sonoff5"
  state_topic: "stat/Sonoff5/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/Sonoff5/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
##############################################################################
- platform: mqtt
  name: "Sonoff6"
  icon: mdi:led-on
  state_topic: "stat/Sonoff6/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/Sonoff6/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
 ##############################################################################
- platform: mqtt
  name: "boiler_handle"
  state_topic: "stat/temp5/POWER"
  command_topic: "cmnd/temp5/POWER"
  availability_topic: "tele/temp5/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
 ##############################################################################
- platform: template
  switches:
    switcher_webapi:
        friendly_name: Boiler
        icon_template: mdi:shower
        # entity_id: sensor.switcher_webapi
        value_template: "{{ is_state('sensor.switcher_webapi_state', 'on') }}"
        turn_on:
            service: script.turn_on
            data:
              entity_id: script.switcher_turn_on
        turn_off:
            service: script.turn_on
            data:
              entity_id: script.switcher_turn_off
################################################################################

- platform: mqtt
  name: "Bathroom light"
  state_topic: "shellies/shellyswitch25-68C63AF966FD/relay/0"
  command_topic: "shellies/shellyswitch25-68C63AF966FD/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
################################################################################
- platform: mqtt
  name: "Balcony Lights"
  state_topic: "shellies/shellyswitch25-68C63AF966F2/relay/0"
  command_topic: "shellies/shellyswitch25-68C63AF966F2/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
################################################################################

