############################################################################
#                                                                          # 
#                               Hub Sensor Light:                          # 
#                                                                          #
############################################################################
  - platform: template
    sensors:
      getway_hub_lm:
        friendly_name: 'עוצמת תאורת חוץ'
        value_template: "{{ states.sensor.illumination_04cf8cf40276.state }}"
############################################################################
#                                                                          # 
#                               Door sensor:                               # 
#                                                                          #
############################################################################
  - platform: template
    sensors:
      door_battery_sensor:
        friendly_name: 'חיישן דלת כניסה'
        unit_of_measurement: '%'
        value_template: "{{ states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level }}"
        icon_template: '{% if states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level == 100 %}
                            mdi:battery
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 90 %}
                            mdi:battery-90
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 80 %}
                            mdi:battery-80
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 70 %}
                            mdi:battery-70
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 60 %}
                            mdi:battery-60
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 50 %}
                            mdi:battery-50
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 40 %}
                            mdi:battery-40
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 30 %}
                            mdi:battery-30
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 20 %}
                            mdi:battery-20
                        {% elif states.binary_sensor.door_window_sensor_158d00039d8d54.attributes.battery_level >= 10 %}
                            mdi:battery-10
                        {% else %}
                            battery-outline
                        {% endif %}'
  - platform: template
    sensors:
        door_status_state:
          friendly_name: 'מצב חיישן דלת'
          #unit_of_measurement: '%'
          value_template: "{{ states.binary_sensor.door_window_sensor_158d00039d8d54.state}}"
  
  ############################################################################
  #                                                                          # 
  #                               Motion sensor:                             #    
  #                                                                          #
  ############################################################################
  - platform: template
    sensors:
      motion_battery_sensor:
        friendly_name: 'חיישן תנועה'
        unit_of_measurement: '%'
        value_template: "{{ states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level }}"
        icon_template: '{% if states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level == 100 %}
                            mdi:battery
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 90 %}
                            mdi:battery-90
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 80 %}
                            mdi:battery-80
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 70 %}
                            mdi:battery-70
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 60 %}
                            mdi:battery-60
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 50 %}
                            mdi:battery-50
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 40 %}
                            mdi:battery-40
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 30 %}
                            mdi:battery-30
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 20 %}
                            mdi:battery-20
                        {% elif states.binary_sensor.motion_sensor_158d00039d81bb.attributes.battery_level >= 10 %}
                            mdi:battery-10
                        {% else %}
                            battery-outline
                        {% endif %}'
  - platform: template
    sensors:
      motion_status_state:
        friendly_name: 'מצב חיישן תנועה'
        #unit_of_measurement: '%'
        value_template: "{{ states.binary_sensor.motion_sensor_158d00039d81bb.state }}"
  ############################################################################
  #                                                                          # 
  #                               Singel Switch sensor:                      #    
  #                                                                          #
  ############################################################################
  - platform: template
    sensors:
      switch_battery_sensor:
        friendly_name: 'מתג מדבקה'
        unit_of_measurement: '%'
        value_template: "{{ states.binary_sensor.switch_158d000394b306.attributes.battery_level }}"
        icon_template: '{% if states.binary_sensor.switch_158d000394b306.attributes.battery_level == 100 %}
                            mdi:battery
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 90 %}
                            mdi:battery-90
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 80 %}
                            mdi:battery-80
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 70 %}
                            mdi:battery-70
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 60 %}
                            mdi:battery-60
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 50 %}
                            mdi:battery-50
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 40 %}
                            mdi:battery-40
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 30 %}
                            mdi:battery-30
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 20 %}
                            mdi:battery-20
                        {% elif states.binary_sensor.switch_158d000394b306.attributes.battery_level >= 10 %}
                            mdi:battery-10
                        {% else %}
                            battery-outline
                        {% endif %}'  
  - platform: template
    sensors:
      switch_status_state:
        friendly_name: 'מצב מתג מדבקה'
        #unit_of_measurement: '%'
        value_template: "{{ states.binary_sensor.switch_158d000394b306.state }}"

  ############################################################################
  #                                                                          # 
  #                               Smart Motion sensor:                       #    
  #                                                                          #
  ############################################################################
  - platform: template
    sensors:
      smart_battery_sensor:
        friendly_name: 'מצב מתג שיאומי חכם'
        unit_of_measurement: '%'
        value_template: "{{ states.switch.plug_158d000391fdca.attributes.battery_level }}"
        icon_template: '{% if states.switch.plug_158d000391fdca.attributes.battery_level == 100 %}
                            mdi:battery
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 90 %}
                            mdi:battery-90
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 80 %}
                            mdi:battery-80
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 70 %}
                            mdi:battery-70
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 60 %}
                            mdi:battery-60
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 50 %}
                            mdi:battery-50
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 40 %}
                            mdi:battery-40
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 30 %}
                            mdi:battery-30
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 20 %}
                            mdi:battery-20
                        {% elif states.switch.plug_158d000391fdca.attributes.battery_level >= 10 %}
                            mdi:battery-10
                        {% else %}
                            battery-outline
                        {% endif %}' 