
#########################################################################
#                                                                       #
#                          Shutter controlling                          #
#                                                                       #
########################################################################
- id: ssias
  alias: Shelly Status Info at Start
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      payload: update
      topic: shellies/command
    service: mqtt.publish
  - data:
      payload: update
      topic: tele/command
    service: mqtt.publish
#########################################################################
#                                                                       #
#                          ON-TIMER boiler_on_timer                     #
#                                                                       #
########################################################################
- id: boiler_on_timer
  alias: 'boiler_on'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.boiler_start_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_on
    entity_id: switch.switcher_touch_d7f2

#########################################################################
#                                                                       #
#                      OFF-TIMER boiler_off_timer                       #
#                                                                       #
########################################################################
- id: boiler_off_timer
  alias: 'boiler_off'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.boiler_end_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_off
    entity_id: switch.switcher_touch_d7f2
  #- service: script.turn_off_boiler
#########################################################################
#                                                                       #
#                          ON-TIMER sonoff3                             #
#                                                                       #
#########################################################################
- id: sonoff3_on_timer
  alias: 'sonoff3_on'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff3_start_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff3
 # - service: script.turn_on_boiler
#########################################################################
#                                                                       #
#                          OFF-TIMER sonoff3                            #
#                                                                       #
#########################################################################
- id: sonoff3_off_timer
  alias: 'sonoff3_off'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff3_end_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff3
 # - service: script.turn_off_boiler
#########################################################################
#                                                                       #
#                          ON-TIMER sonoff2                             #
#                                                                       #
#########################################################################
- id: sonoff2_on_timer
  alias: 'sonoff2_on'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff2_start_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff2
 # - service: script.turn_on_boiler
#########################################################################
#                                                                       #
#                          OFF-TIMER sonoff2                            #
#                                                                       #
#########################################################################
- id: sonoff2_off_timer
  alias: 'sonoff2_off'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff2_end_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff2
 # - service: script.turn_off_boiler
 #########################################################################
#                                                                       #
#                          ON-TIMER sonoff5                             #
#                                                                       #
#########################################################################
- id: sonoff5_on_timer
  alias: 'sonoff5_on'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff5_start_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff5
 # - service: script.turn_on_boiler
#########################################################################
#                                                                       #
#                          OFF-TIMER sonoff5                            #
#                                                                       #
#########################################################################
- id: sonoff5_off_timer
  alias: 'sonoff5_off'
  initial_state: 'on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff5_end_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff5
 # - service: script.turn_off_boiler
 #########################################################################
#                                                                       #
#                          ON-TIMER sonoff6                             #
#                                                                       #
#########################################################################
- id: sonoff6_on_timer
  alias: 'sonoff6_on'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff6_start_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff_10006f9483
 # - service: script.turn_on_boiler
#########################################################################
#                                                                       #
#                          OFF-TIMER sonoff6                            #
#                                                                       #
#########################################################################
- id: sonoff6_off_timer
  alias: 'sonoff6_off'
  trigger:
  - value_template: '{{states(''sensor.time'') == (states.input_datetime.sonoff6_end_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
    platform: template
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff_10006f9483
 # - service: script.turn_off_boiler
#########################################################################
#                                                                       #
#                                                                       #
#                                                                       #
########################################################################
- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
       - service: mqtt.publish
         data:
           topic: "cmnd/saarhome/status"
           payload: "2"
       - service: mqtt.publish
         data:
           topic: "cmnd/saarhome/Status2"
           payload: "2"
#########################################################################
#                                                                       #
#                                                                       #
#                                                                       #
#########################################################################
- id: "sonoff_Status"
  alias: sonoff Status Info at Start
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: saarhome/cmnd/power1
      payload: ""
  - service: mqtt.publish
    data:
      topic: saarhome/cmnd/power2
      payload: ""  
  - service: mqtt.publish
    data:
      topic: saarhome/cmnd/sensor
      payload: ""
#########################################################################
#                                                                       #
#                       Turn on the air Temp                            #
#                                                                       #
#########################################################################
- id: 'אוטומצית  הדלקת מאורר'
  alias: 'sonoff4_temp_on'
  trigger:
  - platform: template
    value_template: '{{ (states.input_number.temp_on.state | float) <= (states.sensor.sonoff4.state | float) }}'
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff4
#########################################################################
#                                                                       #
#                       Turn off the air Temp                           #
#                                                                       #
#########################################################################
- id: 'אוטומציית כיבוי מאורר'
  alias: 'sonoff4_temp_off'
  trigger:
  - platform: template
    value_template: '{{ (states.input_number.temp_off.state | float) >= (states.sensor.sonoff4.state | float) }}'
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff4
#########################################################################
#                                                                       #
#                       Turn on the littel Thrmostat                    #
#                                                                       #
#########################################################################
- id: 'אוטומצית  הדלקת גוף חימום קטן'
  alias: 'sonoff1_temp_on'
  trigger:
  - platform: template
    value_template: '{{ (states.input_number.littel_temp_on.state | float) >= (states.sensor.sonoff1.state | float) }}'
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff1
#########################################################################
#                                                                       #
#                       Turn off the littel Thrmostat                   #
#                                                                       #
#########################################################################
- id: 'אוטומציית כיבוי גוף חימום קטן'
  alias: 'sonoff1_temp_off'
  trigger:
  - platform: template
    value_template: '{{ (states.input_number.littel_temp_off.state | float) <= (states.sensor.sonoff1.state | float) }}'
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff1
########################################################################
- alias: Shutter Open
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000394b306
      click_type: single
  action:
    service: cover.open_cover
    entity_id: cover.livingroom_cover
########################################################################
- alias: Shutter Close
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000394b306
      click_type: double
  action:
    service: cover.stop_cover
    entity_id: cover.livingroom_cover
########################################################################
- alias: Shutter Stop
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000394b306
      click_type: long_click_press
  action:
    service: cover.close_cover
    entity_id: cover.livingroom_cover
########################################################################

- alias: 'Auto Backup'
  trigger:
    platform: time
    at: '08:00:00'
  action:
    service: shell_command.backup_to_hardisk

########################################################################

- id: 'Bathroom Auto Lights on'
  alias: bathroom_light_on
  trigger:
    - entity_id: sensor.motion_2_status_state
      platform: state
      to: '1'
  condition:
    - condition: time
      after: '20:00:00'
      before: '06:00:00'
    # - condition: template
    #  value_template: '{{states(''sensor.time'') == (states.input_datetime.bathroom_start_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom_light

- id: 'Bathroom Auto Lights off'
  alias: bathroom_light_off
  trigger:
    - entity_id: sensor.motion_2_status_state
      platform: state
      to: '0'
      for: 
        minutes: '1' # {{ states('input_number.bathroom_lights_without_motion' ) | int }}"
  condition:
    - condition: time
      after: '20:00:00'
      before: '06:00:00'
    # - condition: template
   #   value_template: '{{states(''sensor.time'') == (states.input_datetime.bathroom_end_time.attributes.timestamp | int | timestamp_custom(''%H:%M'', False))}}'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_light