

- alias: 'Camera record'
  trigger:
    platform: state
    entity_id: sensor.main_door_state
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: "not_home"
    # - condition: sun
    #   before: sunset
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff_1000ad249f_1
  - service: shell_command.cam_shell
  - delay: 40
  - service_template: >
      {% if is_state('group.family', 'not_home') %}
      notify.notify
      {% endif %}
    data:
      title: 'דלת הכניסה לבית נפתחה ואנחנו לא בבית'  #Front Door sensor
      message: 'האור בכניסה לבית נדלק והמצלמה התחילה הקלטה' #front door is open more then 30 sec
######################################################################################################
- alias: 'Send camera recorded'
  trigger:
    platform: state
    entity_id: sensor.main_door_state
    to: 'on'
  condition: []
  action:
  - delay: 60
  - service_template: >
      {% if is_state('group.family', 'not_home') %}
      telegram_bot.send_video
      {% endif %}
    data:
      file: /backup/records/{{ states('sensor.latest_file_in_record_dir')}}
      caption: '{{ now().strftime("%Y-%m-%d %H:%M") }}'
  - service: notify.notify
    data:
      title: 'דלת הכניסה לבית נפתחה ואנחנו לא בבית'  #Front Door sensor
      message: 'נשלחה הלקטה בטלגרם' #front door is open more then 30 sec
  - service: switch.turn_off
    entity_id: switch.sonoff_1000ad249f_1