  temp_on:
    name: טמפ' להדלקה
    initial: 28.5
    min: 25
    max: 35
    step: 0.5
    mode: slider
  temp_off:
    name: טמפ' לכיבוי
    initial: 28
    min: 25
    max: 35
    step: 0.5
    mode: slider
  littel_temp_on:
    name: טמפ' להדלקה
    initial: 27.7
    min: 25
    max: 31
    step: 0.1
    mode: slider
  littel_temp_off:
    name: טמפ' לכיבוי
    initial: 28.5
    min: 25
    max: 31
    step: 0.1
    mode: slider
  bathroom_lights_off:
    name: דקות לכיבוי
    initial: 1
    min: 1
    max: 10
    step: 1
    mode: slider
  bathroom_lights_without_motion:
    name: דקות בלי תזוזה
    initial: 2
    min: 1
    max: 7
    step: 1
    mode: slider
  boiler_target:
    name: מטרה
    initial: 28
    min: 28
    max: 70
    step: 5
    mode: slider
