  temp_on:
    name: טמפ' להדלקה
    initial: 28.5
    min: 25
    max: 35
    step: 0.5
    mode: slider
  temp_off:
    name: טמפ' לכיבוי
    initial: 28
    min: 25
    max: 35
    step: 0.5
    mode: slider
  littel_temp_on:
    name: טמפ' להדלקה
    initial: 27.7
    min: 25
    max: 31
    step: 0.1
    mode: slider
  littel_temp_off:
    name: טמפ' לכיבוי
    initial: 28.5
    min: 25
    max: 31
    step: 0.1
    mode: slider
