##################################################################################
##################################SHELL COMMANDS##################################
##################################################################################
backup_to_hardisk: "bash /config/homeassistant.sh"
homeassistant_updade: !secret update_homeassistant_container

