##################################################################################
##################################SHELL COMMANDS##################################
##################################################################################
backup_to_hardisk: "bash /config/homeassistant.sh"
