info:
    default:
        - icon: '[[icon]]'
        - state:
            - value: "on"
              styles:
                icon: mdi:test
    card:
        type: "custom:button-card"
        entity: '[[entity]]'
        show_state: '[[state]]'
        show_name: '[[show_name]]'
        tap_action:
            action: none
        name: '[[name]]'
        size: 80%
        styles:
            card:
            - height: 80px
            - font-size: 14px
            icon:
            - color: '[[icon_color]]'
info1:
    default:

    card:
        direction: '[[direction]]'
        type: "custom:button-card"
        entity: '[[entity]]'
        show_state: '[[state]]'
        icon: '[[icon]]'
        show_name: '[[show_name]]'
        tap_action:
            action: none
        name: '[[name]]'
        size: 80%
        state:
        styles:
            card:
            - height: 80px
            - font-size: 14px
            icon:
            - color: '[[icon_color]]'

info2:
    default:

    card:
        direction: '[[direction]]'
        type: "custom:slider-entity-row"
        entity: '[[entity]]'
        show_state: '[[state]]'
        icon: '[[icon]]'
        show_name: '[[show_name]]'
        tap_action:
            action: none
        name: '[[name]]'
        size: 80%
        state:
        styles:
            card:
            - height: 80px
            - font-size: 14px
            icon:
            - color: '[[icon_color]]'

