menu_button:
  card:
    aspect_ratio: 1/1
    type: custom:decluttering-card
    template: button
    variables:
      - entity: '[[entity]]'
      - name: '[[name]]'
      - icon: '[[icon]]'
      - color: '[[color]]'
      - font-family: tahoma
      - color_type: '[[color_type]]'
      - corner_text_color: "[[corner_text_color]]"
      - corner_icon_color: "[[[
          if (entity.state == 'off') return 'var(--paper-item-icon-color)';
          else return 'var(--paper-item-icon-active-color)';
          ]]]"
      - corner_2_text_color: "[[corner_2_text_color]]"
      - corner_2_icon_color: "[[corner_2_icon_color]]"
      - cust_1_text_color: "[[cust_1_text_color]]"
      - cust_1_icon_color: "[[cust_1_icon_color]]"
      - cust_2_text_color: "[[cust_2_text_color]]"
      - cust_2_icon_color: "[[cust_2_icon_color]]"
      - corner_field: "[[[
          if (entity.state == 'off')
          return `<ha-icon icon='mdi:lightbulb' style='width: 18px; height: 18px; color: var(--icon-color-sensor);'></ha-icon>`;
          else return `<ha-icon icon='mdi:lightbulb' style='width: 18px; height: 18px; color: var(--icon-color-sensor);'></ha-icon>`;
          ]]]"
      - corner_2_field: "[[corner_2_field]]"
      - cust_1_field: "[[cust_1_field]]"
      - cust_2_field: "[[cust_2_field]]"
      - tap_action: 
          action: '[[action]]'
          # navigation_path: /lovelace/[[path]]/
      - hold_action:
          action: more-info
      - state:
        - value: "on"
          styles:
            icon:
              - color: var(--paper-item-icon-color)