title:
    card:
        type: "custom:button-card"
        color_type: label-card
        name: -[[name]]-
        styles:
            card:
            - height: 20px
            - text-transform: none
            - color: black
            - background-color: rgb(211,211,211,0.6)
            - font-size: 20px
            - font-weight: bold
            - font-family: Helvetica