tv:
    default:
        - icon: '[[icon]]'
        - state:
            - value: "on"
              styles:
                icon: mdi:test
    card:
        type: "custom:button-card"
        #template: '[[template]]'
        entity: '[[entity]]'
        show_state: '[[state]]'
        show_name: '[[show_name]]'
        icon: '[[icon]]'
        tap_action:
            service: '[[service]]'
            action: '[[action]]'     
            service_data:
              entity_id: '[[entity]]'
        name: '[[name]]'
        size: 80%
        styles:
            card:
            - height: 80px
            - font-size: 14px
            icon:
            - color: '[[icon_color]]'

            
